#!/bin/bash

# doit - make all or some example picture sets.

# Usage: doit      # make them all
#        doit nnx  # make nnx.pdf and snnx.pdf
#
# pictures are numbered 01, 02, etc.
# nn[a-z] has code to typeset a \ctable; for nn[k-z] page layout will be shown
# for each nn[a-z] two pdfs are generated:
#      nn[a-z].pdf for the ctable picture
# and snn[a-z].pdf for the source code verbatim.
# The prefix (s) for source verbatims and (empty) for result files is set by PRE
set=${1:-[0-9][0-9][a-z]}
for j in $set; do
   # source verbatim
   { cat <<-'EOD'
	\documentclass{article}
	\usepackage[a4paper,margin=20mm,noheadfoot]{geometry}
	\pagestyle{empty}
	\begin{document}\ttfamily
	\fontsize{10}{12pt}\selectfont
	\begin{verbatim}
	EOD
	grep -v "remove from source" "$j"
	cat <<-'EOD'
	\end{verbatim}
	\end{document}
	EOD
   } >s"$j".tex

   echo x | lualatex s"$j".tex &>/dev/null || die "lualatex failed on s$j"
   rm s"$j".{aux,tex,log}
   pdfcrop s"$j".pdf s"$j".pdf >& /dev/null
   # result
   { echo '\documentclass[twoside]{article}'
     [[ $j =~ [k-z] ]] && echo '\usepackage[papersize={56mm,40mm},showframe,margin=1mm,noheadfoot]{geometry}'
     cat <<-'EOD'
	\usepackage{ctable}
	\usepackage{fontspec}
	\usepackage{microtype}
	\makeatletter\def\MT@warn@unknown{}\makeatother
	\setmainfont[Ligatures=TeX]{Fontin-Regular}[%
	     ItalicFont=Fontin-Italic,
             BoldFont=Fontin-Bold,
             SmallCapsFont=Fontin-SmallCaps
            ]
	\setmonofont{DejaVuSansMono}[Scale=MatchLowercase]

	\pagestyle{empty}
	\parindent0pt
	\begin{document}
	EOD
     cat "$j"
     echo '\end{document}'
   } > "$j".tex
   echo x | lualatex "$j".tex &>/dev/null || die "lualatex failed on $j"
   rm "$j".{aux,tex,log}
   pdfcrop "$j".pdf "$j".pdf >& /dev/null
   printf "\r%d%%" $((n+=4))
done
echo -ne "\r    \r"
