#!/bin/sh

# doit - make all or one example picture sets.

# Usage: doit       # make them all
#        doit nn    # make set nn
#
# pictures are numbered 01, 02, etc.
# nn has description text
# nn[a-z] has code to typeset a \ctable; for [k-z] page layout will be shown
# for each nn[a-z] two pdfs are generated: nn[a-z].pdf for the ctable picture
#     and snn[a-z].pdf for the source code verbatim.

if [ "$1" = "" ]; then 
  new=`ls [0-9][0-9]`
else
  if [ ! -e $1 ]; then
    echo "Error: file $1 not found"
    exit 1
  fi
  new=$1
fi

cat <<'EOF' >main.tex || exit 1
\documentclass[12pt]{article}
\usepackage{ctable,verbatfi,colortbl,doc}
\usepackage{pxfonts}
\definecolor{lightblue}{rgb}{0.529, 0.808, 0.922}
\definecolor{lightyellow}{rgb}{1,1,.878}
\MakeShortVerb{\|}
\parindent0pt\parskip2ex
\setcounter{secnumdepth}{1}
\begin{document}
EOF

temp=`mktemp`
for i in $new; do 
  cat $i |grep -v ^\$Id >> main.tex
  echo -e '\n\\begin{tabularx}{\hsize}{>{\\hsize=.5\\hsize\\center}X>{\\hsize=.5\\hsize\\center}X}' >>main.tex
  for j in $i[a-z]; do 
    echo '\documentclass[twoside]{article}' >$j.tex
    echo $j|grep "[k-z]$" >/dev/null &&
      echo '\usepackage[papersize={65mm,40mm},showframe,margin=5mm,noheadfoot]{geometry}' >>$j.tex
    echo '\usepackage{ctable}
      \usepackage{txfonts}
      \pagestyle{empty}
      \parindent0pt
      \begin{document}
    ' >>$j.tex
    cat $j |grep -v "^\$Id" >> $j.tex
    echo '\end{document}' >> $j.tex
    mk --noview --noprint $j.tex || exit 1 # mk: CTAN see catalogue
    pdfcrop $j.pdf $j.pdf
    asc2pdf $j --batch=o$temp
    if ! pdfcrop --margins 2 $temp.pdf s$j.pdf 2>/dev/null; then
       echo error running "pdfcrop --margins 2 $temp.pdf s$j.pdf"
       exit 1
    else 
      rm -f $temp $temp.pdf
    fi
    if [ $j = $i'a' -o $j = $i'k' ]; then 
      echo -n '\rowcolor{lightyellow}' >> main.tex
    else
      echo -n '\rowcolor{lightblue}' >> main.tex
    fi
    echo '\includegraphics{s'$j'}& \includegraphics{'$j'}\NN' >> main.tex
    case $j in
    *[ak]*) echo '\rowcolor{lightyellow} & \NN' >> main.tex;;
    *)    echo '\rowcolor{lightblue} & \NN' >> main.tex;;
    esac
  done
  echo -e '\\end{tabularx}\n' >>main.tex
done
echo '\end{document}' >>main.tex
mk --noview --noprint

# $Id$
